import axios from "axios";
import Head from "next/head";
import { useState } from "react";

export default function Home() {
  const [ip, setIp] = useState("");
  return (
    <>
      <Head>
        <title>Digital Fingerprint</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <p className="bg-green-300">jcbakjcbaskc</p>
      </main>
    </>
  );
}
